Repository doctrine/cache, pull requests merged in 2018-12, with the labels that each got.

#294 update broken link
  README.md
Labels: Documentation

#296 point to the current version of the docs
  README.md
Labels: Documentation

#293 Alias Riak\Object as RiakObject to prevent errors in PHP 7.2
  lib/Doctrine/Common/Cache/RiakCache.php
Labels: Bug

#297 Use Ubuntu 16.04
  .travis.yml
Labels: Enhancement
