Repository doctrine/cache, pull requests merged in 2019-11, with the labels that each got.

#318 Add .github folder to .gitattributes
  .gitattributes
Labels: Enhancement

#319 Backport #293 into 1.8.x
  lib/Doctrine/Common/Cache/RiakCache.php
Labels: Bug

#322 Add .doctrine-project.json to .gitattributes
  .gitattributes
Labels: Enhancement

#307 Changed RedisCache to use pipeline in operations with multiple keys
  lib/Doctrine/Common/Cache/RedisCache.php
Labels: Enhancement

#324 Drop RiakCache support
  .travis.yml
  composer.json
  docs/en/index.rst
  lib/Doctrine/Common/Cache/RiakCache.php
  phpunit.xml.dist
  tests/Doctrine/Tests/Common/Cache/RiakCacheTest.php
Labels: Bug

#328 Fix flaky MongoDB test
  tests/Doctrine/Tests/Common/Cache/ExtMongoDBCacheTest.php
Labels: Bug

#330 Fix typo in `Redis` cache implementation
  lib/Doctrine/Common/Cache/RedisCache.php
Labels: Bug

#308 Prevent invalid memcached key to be used
  lib/Doctrine/Common/Cache/InvalidCacheId.php
  lib/Doctrine/Common/Cache/MemcachedCache.php
  tests/Doctrine/Tests/Common/Cache/MemcachedCacheTest.php
Labels: Improvement

#334 Support php 7.4
  .travis.yml
  tests/travis/Couchbase.sh
Labels: Improvement
