Repository doctrine/cache, pull requests merged in 2022-05, with the labels that each got.

#400 Disable fail-fast
  .github/workflows/continuous-integration.yml
Labels: CI

#391 Add example of using a PSR-6 cache wrapped in Doctrine Cache interface.
  UPGRADE-1.11.md
  docs/en/index.rst
Labels: Documentation

#403 Skip broken memcached tests
  tests/Doctrine/Tests/Common/Cache/MemcachedCacheTest.php
Labels: CI

#405 Remove obsolete dependencies
  .github/workflows/continuous-integration.yml
  composer.json
Labels: CI

#398 Add reset() to PSR-6 DoctrineProvider
  lib/Doctrine/Common/Cache/Psr6/DoctrineProvider.php
  tests/Doctrine/Tests/Common/Cache/Psr6/DoctrineProviderTest.php
Labels: Enhancement
